/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_demofx_ZhoWrapper */

#ifndef _Included_org_example_demofx_ZhoWrapper
#define _Included_org_example_demofx_ZhoWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1new
  (JNIEnv *, jobject);

/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_convert
 * Signature: (J[B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1convert
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_get_parallel
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1get_1parallel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_set_parallel
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1set_1parallel
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_zho_check
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1zho_1check
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_example_demofx_ZhoWrapper
 * Method:    opencc_last_error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_example_demofx_ZhoWrapper_opencc_1last_1error
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
